// Datos de ejemplo para la aplicación

export const MOCK_GAMES = [
  {
    id: '1',
    title: 'Hades',
    description: 'Desafía al dios de los muertos mientras te abres paso para salir del Inframundo en este juego de rol roguelike de los creadores de Bastion y Transistor.',
    price: 24.99,
    discount_percent: 20,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/ss_c0fed447426b69981cf1721756acf75369801b31.1920x1080.jpg',
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    tags: ['Roguelike', 'Acción', 'Indie'],
    release_date: '2020-09-17',
  },
  {
    id: '2',
    title: 'Cyberpunk 2077',
    description: 'Cyberpunk 2077 es un RPG de aventura y acción de mundo abierto ambientado en el futuro sombrío de Night City, una peligrosa megalópolis obsesionada con el poder, el glamur y la modificación corporal.',
    price: 59.99,
    discount_percent: 0,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_b529b0abc43f55fc23fe51efe0a8c9b4ebb9d4a6.1920x1080.jpg',
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    tags: ['RPG', 'Mundo abierto', 'Futurista'],
    release_date: '2020-12-10',
  },
  {
    id: '3',
    title: 'Hollow Knight',
    description: 'Forja tu propio camino en Hollow Knight, una aventura de acción épica a través de un vasto reino en ruinas de insectos y héroes.',
    price: 14.99,
    discount_percent: 33,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/ss_29ef4b3c69901bfaf986e31f0ca0147c1d2d1a0f.1920x1080.jpg',
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    tags: ['Metroidvania', 'Difícil', 'Indie'],
    release_date: '2017-02-24',
  },
  {
    id: '4',
    title: 'Elden Ring',
    description: 'EL NUEVO RPG DE ACCIÓN DE FANTASÍA. Álzate, Sinluz, y que la gracia te guíe para abrazar el poder del Círculo de Elden y convertirte en un Señor de Elden en las Tierras Intermedias.',
    price: 59.99,
    discount_percent: 0,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/ss_e80a45f18e72b9501653cddc0d43a5aa3aaec542.1920x1080.jpg',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    tags: ['Souls-like', 'Mundo abierto', 'Difícil'],
    release_date: '2022-02-25',
  },
  {
    id: '5',
    title: 'Stardew Valley',
    description: 'Acabas de heredar la vieja parcela agrícola de tu abuelo en Stardew Valley. Con herramientas de segunda mano y algunas monedas, comienzas tu nueva vida.',
    price: 14.99,
    discount_percent: 0,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_b887651a93b0525739049eb4194f633de2d5ae55.1920x1080.jpg',
    developer: 'ConcernedApe',
    publisher: 'ConcernedApe',
    tags: ['Simulación', 'RPG', 'Indie'],
    release_date: '2016-02-26',
  },
  {
    id: '6',
    title: 'Red Dead Redemption 2',
    description: 'América, 1899. El ocaso del Salvaje Oeste ha comenzado y las fuerzas de la ley dan caza a las últimas bandas de forajidos. Los que no se rinden o sucumben, son asesinados.',
    price: 59.99,
    discount_percent: 50,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_bac60bacbf5da8945103648c08d27d5e202444ca.1920x1080.jpg',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    tags: ['Mundo abierto', 'Aventura', 'Western'],
    release_date: '2019-12-05',
  },
  {
    id: '7',
    title: 'Halo Infinite',
    description: 'Cuando toda esperanza está perdida y el destino de la humanidad pende de un hilo, el Jefe Maestro está listo para enfrentarse al enemigo más despiadado al que jamás haya hecho frente.',
    price: 59.99,
    discount_percent: 20,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/ss_8874d0394d1eb9e158c0c8c2b68794d0e22b9a2e.1920x1080.jpg',
    developer: '343 Industries',
    publisher: 'Xbox Game Studios',
    tags: ['FPS', 'Multijugador', 'Ciencia ficción'],
    release_date: '2021-12-08',
  },
  {
    id: '8',
    title: 'Celeste',
    description: 'Ayuda a Madeline a sobrevivir a su viaje interior en su ascenso a la cima de la Montaña Celeste, en este ajustado plataformas de los creadores de TowerFall.',
    price: 19.99,
    discount_percent: 50,
    image_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg',
    banner_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/ss_4b0f0467de01dc81b48d01a79f723b4e708a3f52.1920x1080.jpg',
    developer: 'Extremely OK Games',
    publisher: 'Extremely OK Games',
    tags: ['Plataformas', 'Difícil', 'Indie'],
    release_date: '2018-01-25',
  },
];

export const MOCK_USER = {
  id: 'user-1',
  email: 'usuario@ejemplo.com',
  username: 'GamerPro',
  avatar_url: null,
};

export const MOCK_USER_GAMES = [
  {
    id: 'ug-1',
    game_id: '1',
    last_played: new Date(2023, 5, 15).toISOString(),
    playtime_minutes: 120,
    ...MOCK_GAMES[0],
  },
  {
    id: 'ug-2',
    game_id: '3',
    last_played: new Date(2023, 6, 20).toISOString(),
    playtime_minutes: 360,
    ...MOCK_GAMES[2],
  },
];
